#############################################################################
# Makefile for building: robot_simulator
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  robot_simulator.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile robot_simulator.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = robot_simulator1.0.0
DISTDIR = /mnt/c/Users/espatie1/ICP_project/.tmp/robot_simulator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/code/AutonomousRobot.cpp \
		src/code/ConfigManager.cpp \
		src/code/Environment.cpp \
		src/code/main.cpp \
		src/code/Obstacle.cpp \
		src/code/RemoteControlledRobot.cpp \
		src/code/Robot.cpp \
		src/code/SimulationEngine.cpp \
		src/code/Utilities.cpp \
		src/gui/ControlPanel.cpp \
		src/gui/GuiMain.cpp \
		src/gui/LoadEnvironment.cpp \
		src/gui/ObstacleDialog.cpp \
		src/gui/ObstacleView.cpp \
		src/gui/RobotDialog.cpp \
		src/gui/RobotView.cpp \
		src/gui/SettingsDialog.cpp \
		src/gui/SimulationWindow.cpp moc_SimulationEngine.cpp \
		moc_ControlPanel.cpp \
		moc_GuiMain.cpp \
		moc_LoadEnvironment.cpp \
		moc_ObstacleDialog.cpp \
		moc_RobotDialog.cpp \
		moc_SettingsDialog.cpp \
		moc_SimulationWindow.cpp
OBJECTS       = AutonomousRobot.o \
		ConfigManager.o \
		Environment.o \
		main.o \
		Obstacle.o \
		RemoteControlledRobot.o \
		Robot.o \
		SimulationEngine.o \
		Utilities.o \
		ControlPanel.o \
		GuiMain.o \
		LoadEnvironment.o \
		ObstacleDialog.o \
		ObstacleView.o \
		RobotDialog.o \
		RobotView.o \
		SettingsDialog.o \
		SimulationWindow.o \
		moc_SimulationEngine.o \
		moc_ControlPanel.o \
		moc_GuiMain.o \
		moc_LoadEnvironment.o \
		moc_ObstacleDialog.o \
		moc_RobotDialog.o \
		moc_SettingsDialog.o \
		moc_SimulationWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		robot_simulator.pro src/code/AutonomousRobot.h \
		src/code/ConfigManager.h \
		src/code/Environment.h \
		src/code/Obstacle.h \
		src/code/RemoteControlledRobot.h \
		src/code/Robot.h \
		src/code/SimulationEngine.h \
		src/code/Utilities.h \
		src/gui/ControlPanel.h \
		src/gui/GuiMain.h \
		src/gui/LoadEnvironment.h \
		src/gui/ObstacleDialog.h \
		src/gui/ObstacleView.h \
		src/gui/RobotDialog.h \
		src/gui/RobotView.h \
		src/gui/SettingsDialog.h \
		src/gui/SimulationWindow.h src/code/AutonomousRobot.cpp \
		src/code/ConfigManager.cpp \
		src/code/Environment.cpp \
		src/code/main.cpp \
		src/code/Obstacle.cpp \
		src/code/RemoteControlledRobot.cpp \
		src/code/Robot.cpp \
		src/code/SimulationEngine.cpp \
		src/code/Utilities.cpp \
		src/gui/ControlPanel.cpp \
		src/gui/GuiMain.cpp \
		src/gui/LoadEnvironment.cpp \
		src/gui/ObstacleDialog.cpp \
		src/gui/ObstacleView.cpp \
		src/gui/RobotDialog.cpp \
		src/gui/RobotView.cpp \
		src/gui/SettingsDialog.cpp \
		src/gui/SimulationWindow.cpp
QMAKE_TARGET  = robot_simulator
DESTDIR       = 
TARGET        = robot_simulator


first: all
####### Build rules

robot_simulator:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: robot_simulator.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		robot_simulator.pro
	$(QMAKE) -o Makefile robot_simulator.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
robot_simulator.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile robot_simulator.pro

qmake_all: FORCE


all: Makefile robot_simulator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/code/AutonomousRobot.h src/code/ConfigManager.h src/code/Environment.h src/code/Obstacle.h src/code/RemoteControlledRobot.h src/code/Robot.h src/code/SimulationEngine.h src/code/Utilities.h src/gui/ControlPanel.h src/gui/GuiMain.h src/gui/LoadEnvironment.h src/gui/ObstacleDialog.h src/gui/ObstacleView.h src/gui/RobotDialog.h src/gui/RobotView.h src/gui/SettingsDialog.h src/gui/SimulationWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/code/AutonomousRobot.cpp src/code/ConfigManager.cpp src/code/Environment.cpp src/code/main.cpp src/code/Obstacle.cpp src/code/RemoteControlledRobot.cpp src/code/Robot.cpp src/code/SimulationEngine.cpp src/code/Utilities.cpp src/gui/ControlPanel.cpp src/gui/GuiMain.cpp src/gui/LoadEnvironment.cpp src/gui/ObstacleDialog.cpp src/gui/ObstacleView.cpp src/gui/RobotDialog.cpp src/gui/RobotView.cpp src/gui/SettingsDialog.cpp src/gui/SimulationWindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_SimulationEngine.cpp moc_ControlPanel.cpp moc_GuiMain.cpp moc_LoadEnvironment.cpp moc_ObstacleDialog.cpp moc_RobotDialog.cpp moc_SettingsDialog.cpp moc_SimulationWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SimulationEngine.cpp moc_ControlPanel.cpp moc_GuiMain.cpp moc_LoadEnvironment.cpp moc_ObstacleDialog.cpp moc_RobotDialog.cpp moc_SettingsDialog.cpp moc_SimulationWindow.cpp
moc_SimulationEngine.cpp: src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/code/SimulationEngine.h -o moc_SimulationEngine.cpp

moc_ControlPanel.cpp: src/gui/ControlPanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/ControlPanel.h -o moc_ControlPanel.cpp

moc_GuiMain.cpp: src/gui/GuiMain.h \
		src/gui/SimulationWindow.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h \
		src/code/ConfigManager.h \
		src/gui/RobotView.h \
		src/gui/ObstacleView.h \
		src/gui/RobotDialog.h \
		src/gui/ObstacleDialog.h \
		src/gui/ControlPanel.h \
		src/gui/SettingsDialog.h \
		src/gui/LoadEnvironment.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/GuiMain.h -o moc_GuiMain.cpp

moc_LoadEnvironment.cpp: src/gui/LoadEnvironment.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/LoadEnvironment.h -o moc_LoadEnvironment.cpp

moc_ObstacleDialog.cpp: src/gui/ObstacleDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/ObstacleDialog.h -o moc_ObstacleDialog.cpp

moc_RobotDialog.cpp: src/gui/RobotDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/RobotDialog.h -o moc_RobotDialog.cpp

moc_SettingsDialog.cpp: src/gui/SettingsDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/SettingsDialog.h -o moc_SettingsDialog.cpp

moc_SimulationWindow.cpp: src/gui/SimulationWindow.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h \
		src/code/ConfigManager.h \
		src/gui/RobotView.h \
		src/gui/ObstacleView.h \
		src/gui/RobotDialog.h \
		src/gui/ObstacleDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/espatie1/ICP_project/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/espatie1/ICP_project -I/mnt/c/Users/espatie1/ICP_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/SimulationWindow.h -o moc_SimulationWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

AutonomousRobot.o: src/code/AutonomousRobot.cpp src/code/AutonomousRobot.h \
		src/code/Robot.h \
		src/code/Environment.h \
		src/code/Obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AutonomousRobot.o src/code/AutonomousRobot.cpp

ConfigManager.o: src/code/ConfigManager.cpp src/code/ConfigManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigManager.o src/code/ConfigManager.cpp

Environment.o: src/code/Environment.cpp src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/RemoteControlledRobot.h \
		src/code/AutonomousRobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Environment.o src/code/Environment.cpp

main.o: src/code/main.cpp src/gui/GuiMain.h \
		src/gui/SimulationWindow.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h \
		src/code/ConfigManager.h \
		src/gui/RobotView.h \
		src/gui/ObstacleView.h \
		src/gui/RobotDialog.h \
		src/gui/ObstacleDialog.h \
		src/gui/ControlPanel.h \
		src/gui/SettingsDialog.h \
		src/gui/LoadEnvironment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/code/main.cpp

Obstacle.o: src/code/Obstacle.cpp src/code/Obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obstacle.o src/code/Obstacle.cpp

RemoteControlledRobot.o: src/code/RemoteControlledRobot.cpp src/code/RemoteControlledRobot.h \
		src/code/Robot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RemoteControlledRobot.o src/code/RemoteControlledRobot.cpp

Robot.o: src/code/Robot.cpp src/code/Robot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Robot.o src/code/Robot.cpp

SimulationEngine.o: src/code/SimulationEngine.cpp src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimulationEngine.o src/code/SimulationEngine.cpp

Utilities.o: src/code/Utilities.cpp src/code/Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utilities.o src/code/Utilities.cpp

ControlPanel.o: src/gui/ControlPanel.cpp src/gui/ControlPanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ControlPanel.o src/gui/ControlPanel.cpp

GuiMain.o: src/gui/GuiMain.cpp src/gui/GuiMain.h \
		src/gui/SimulationWindow.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h \
		src/code/ConfigManager.h \
		src/gui/RobotView.h \
		src/gui/ObstacleView.h \
		src/gui/RobotDialog.h \
		src/gui/ObstacleDialog.h \
		src/gui/ControlPanel.h \
		src/gui/SettingsDialog.h \
		src/gui/LoadEnvironment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GuiMain.o src/gui/GuiMain.cpp

LoadEnvironment.o: src/gui/LoadEnvironment.cpp src/gui/LoadEnvironment.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/ConfigManager.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoadEnvironment.o src/gui/LoadEnvironment.cpp

ObstacleDialog.o: src/gui/ObstacleDialog.cpp src/gui/ObstacleDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObstacleDialog.o src/gui/ObstacleDialog.cpp

ObstacleView.o: src/gui/ObstacleView.cpp src/gui/ObstacleView.h \
		src/code/Obstacle.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObstacleView.o src/gui/ObstacleView.cpp

RobotDialog.o: src/gui/RobotDialog.cpp src/gui/RobotDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RobotDialog.o src/gui/RobotDialog.cpp

RobotView.o: src/gui/RobotView.cpp src/gui/RobotView.h \
		src/code/Robot.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RobotView.o src/gui/RobotView.cpp

SettingsDialog.o: src/gui/SettingsDialog.cpp src/gui/SettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SettingsDialog.o src/gui/SettingsDialog.cpp

SimulationWindow.o: src/gui/SimulationWindow.cpp src/gui/SimulationWindow.h \
		src/code/SimulationEngine.h \
		src/code/Environment.h \
		src/code/Robot.h \
		src/code/Obstacle.h \
		src/code/AutonomousRobot.h \
		src/code/RemoteControlledRobot.h \
		src/code/ConfigManager.h \
		src/gui/RobotView.h \
		src/gui/ObstacleView.h \
		src/gui/RobotDialog.h \
		src/gui/ObstacleDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimulationWindow.o src/gui/SimulationWindow.cpp

moc_SimulationEngine.o: moc_SimulationEngine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimulationEngine.o moc_SimulationEngine.cpp

moc_ControlPanel.o: moc_ControlPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ControlPanel.o moc_ControlPanel.cpp

moc_GuiMain.o: moc_GuiMain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GuiMain.o moc_GuiMain.cpp

moc_LoadEnvironment.o: moc_LoadEnvironment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoadEnvironment.o moc_LoadEnvironment.cpp

moc_ObstacleDialog.o: moc_ObstacleDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ObstacleDialog.o moc_ObstacleDialog.cpp

moc_RobotDialog.o: moc_RobotDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RobotDialog.o moc_RobotDialog.cpp

moc_SettingsDialog.o: moc_SettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SettingsDialog.o moc_SettingsDialog.cpp

moc_SimulationWindow.o: moc_SimulationWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimulationWindow.o moc_SimulationWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

